# Generated by Django 6.0.5 on 2026-05-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='LocationOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Farg‘ona', 'Farg‘ona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo')], default='Toshkent', max_length=30, verbose_name='Viloyat')),
                ('street', models.CharField(max_length=150)),
                ('home', models.CharField(max_length=30)),
                ('house', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mashina nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('color', models.CharField(max_length=50, verbose_name='Rangi')),
                ('year', models.PositiveIntegerField(verbose_name='Ishlab chiqarilgan yil')),
                ('mileage', models.PositiveIntegerField(verbose_name='Yurgani (KM)')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('used', 'Ishlatilgan')], max_length=20, verbose_name='Holati')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.category', verbose_name='Kategoriya')),
            ],
        ),
    ]
