# Generated by Django 6.0.5 on 2026-05-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='other_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('chevrolet', 'Chevrolet'), ('kia', 'Kia'), ('hyundai', 'Hyundai'), ('byd', 'BYD'), ('chery', 'Chery'), ('toyota', 'Toyota'), ('lada', 'Lada'), ('uaz', 'UAZ'), ('gaz', 'GAZ'), ('honda', 'Honda'), ('nissan', 'Nissan'), ('lexus', 'Lexus'), ('mikroavtobus', 'Mikroavtobus'), ('avtobus', 'Avtobus'), ('yuk_mashinasi', 'Yuk mashinasi'), ('maxsus_texnika', 'Maxsus texnika'), ('Skuter', 'Skuter'), ('Moped', 'Moped'), ('Mototsikl', 'Mototsikl'), ('Yengil avtomobil', 'Yengil avtomobil'), ('Pickup', 'Pikap'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya nomi'),
        ),
    ]
