# Generated by Django 6.0.5 on 2026-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_category_other_brand_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('chevrolet', 'Chevrolet'), ('kia', 'Kia'), ('hyundai', 'Hyundai'), ('byd', 'BYD'), ('chery', 'Chery'), ('toyota', 'Toyota'), ('lada', 'Lada'), ('uaz', 'UAZ'), ('gaz', 'GAZ'), ('honda', 'Honda'), ('nissan', 'Nissan'), ('lexus', 'Lexus'), ('mikroavtobus', 'Mikroavtobus'), ('avtobus', 'Avtobus'), ('yuk_mashinasi', 'Yuk mashinasi'), ('maxsus_texnika', 'Maxsus texnika'), ('skuter', 'Skuter'), ('moped', 'Moped'), ('mototsikl', 'Mototsikl'), ('yengil_avtomobil', 'Yengil avtomobil'), ('pickup', 'Pikap'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='car',
            name='other_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Boshqa marka'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
