# Generated by Django 6.0.5 on 2026-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_car_category_car_other_brand_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationOfProduct',
            new_name='LocationOfProductModel',
        ),
    ]
