# Generated by Django 6.0.5 on 2026-05-16 10:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_email_verified_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('sotuvchi', 'Sotuvchi'), ('haridor', 'Haridor')], default='sotuvchi', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 dan boshlanishi kerak', regex='^\\+?998\\d{9}$')]),
        ),
    ]
