# Generated by Django 6.0.5 on 2026-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_date_of_register_customuser_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('sotuvchi', 'Sotuvchi'), ('haridor', 'Haridor')], default='haridor', max_length=20),
        ),
    ]
