# Generated by Django 6.0.5 on 2026-05-16 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 dan boshlanishi kerak', regex='^\\+?998\\d{9}$')]),
        ),
    ]
